KafkaServer {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="eshop_platform_kafka_broker"
    password="password";
};

KafkaClient {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="eshop_platform_kafka_client"
    password="password";
};

Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_eshop_platform_kafka_broker_client="password";
};

Client {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="eshop_platform_kafka_broker_client"
    password="password";
};