apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: simonsenic/user-service
        ports:
        - containerPort: 8080